# Configuration file for MegaLinter - github_action repository
# See all available variables at https://megalinter.io/latest/config-file/

# Apply fixes for formatters
APPLY_FIXES: all
APPLY_FIXES_EVENT: all
APPLY_FIXES_MODE: commit

# Validate all codebase
VALIDATE_ALL_CODEBASE: true

# Essential Python linters - consistent local & CI setup
# - ruff: Fast, modern linter (flake8 + pylint)
# - pylint: Comprehensive, configured in each repo's pyproject.toml
# - black, mypy, isort: Formatters & type checkers
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - PYTHON_BLACK
  - PYTHON_ISORT
  - PYTHON_RUFF
  - PYTHON_PYLINT
  - PYTHON_MYPY
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - REPOSITORY_GITLEAKS
  - REPOSITORY_TRIVY
  - SPELL_LYCHEE

# Disable redundant linters to reduce runtime and false positives
DISABLE_LINTERS:
  - PYTHON_FLAKE8           # Redundant with ruff
  - PYTHON_PYRIGHT          # Duplicate type checker; mypy is sufficient

# ActionLint configuration for workflow validation
ACTION_ACTIONLINT_CONFIG_FILE: .github/actionlint.yaml

# Python configuration - respects each repo's pyproject.toml
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_PYLINT_CONFIG_FILE: pyproject.toml

# YAML formatting
YAML_PRETTIER_ARGUMENTS: '--single-quote'

# Display output options
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: true
SHOW_LINTER_TIMINGS: true

# Disable LLM advisor and flavor suggestions
LLM_ADVISOR_ENABLED: false
FLAVOR_SUGGESTIONS: false

# Fail on errors
DISABLE_ERRORS: false

# Post comment on PR
POST_COMMENT: true
