# Configuration file for MegaLinter - github_action repository
# See all available variables at https://megalinter.io/latest/config-file/

# Apply fixes for formatters
APPLY_FIXES: all
APPLY_FIXES_EVENT: all
APPLY_FIXES_MODE: commit

# Validate all codebase
VALIDATE_ALL_CODEBASE: true

# Essential Python linters - consistent local & CI setup
# - ruff: Fast, modern linter (flake8 + pylint)
# - pylint: Comprehensive, configured in each repo's pyproject.toml
# - black, mypy, isort: Formatters & type checkers
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - PYTHON_BLACK
  - PYTHON_ISORT
  - PYTHON_RUFF
  - PYTHON_PYLINT
  - PYTHON_MYPY
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - REPOSITORY_GITLEAKS
  - REPOSITORY_TRIVY
  - SPELL_LYCHEE

# Disable redundant linters to reduce runtime and false positives
DISABLE_LINTERS:
  - PYTHON_FLAKE8           # Redundant with ruff
  - PYTHON_PYRIGHT          # Duplicate type checker; mypy is sufficient

# ActionLint configuration for workflow validation
ACTION_ACTIONLINT_CONFIG_FILE: .github/actionlint.yaml

# Python configuration
# pylint: Use .pylintrc (INI format) if available, otherwise default
# Others: Use pyproject.toml (TOML format) for their configuration
PYTHON_BLACK_CONFIG_FILE: pyproject.toml
PYTHON_ISORT_CONFIG_FILE: pyproject.toml
PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_RUFF_CONFIG_FILE: pyproject.toml
PYTHON_PYLINT_CONFIG_FILE: .pylintrc
# Exclude .github scripts and tests from pylint (they have separate standards)
PYTHON_PYLINT_FILTER_REGEX_EXCLUDE: ".github/script/.*|tests/.*"

# Markdown configuration - ignore doc folders in all repos
MARKDOWN_MARKDOWNLINT_FILTER_REGEX_EXCLUDE: "doc/"

# YAML formatting
YAML_PRETTIER_ARGUMENTS: '--single-quote'

# Display output options
SHOW_ELAPSED_TIME: true
SHOW_SKIPPED_LINTERS: true
SHOW_LINTER_TIMINGS: true

# Disable LLM advisor and flavor suggestions
LLM_ADVISOR_ENABLED: false
FLAVOR_SUGGESTIONS: false

# Fail on errors
DISABLE_ERRORS: false

# Post comment on PR - Let MegaLinter handle PR comments natively
POST_COMMENT: true
# Pre-commands: Install native dependencies and Python packages before linting
# Builds librdkafka from source to ensure modern version compatible with confluent-kafka
PRE_COMMANDS:
  # 1) Toolchain + pkgconf + common codec/SSL/SASL dev headers
  - command: |
      set -eux
      apk add --no-cache \
        build-base python3-dev pkgconf \
        openssl-dev zlib-dev lz4-dev zstd-dev \
        cyrus-sasl-dev curl-dev git
    cwd: root
    run_before_linters: true
    continue_if_failed: false

  # 2) Build and install librdkafka >= 2.12.1 from source
  - command: |
      set -eux
      cd /tmp
      # Use official Confluent repository (moved from edenhill)
      git clone https://github.com/confluentinc/librdkafka.git
      cd librdkafka
      # Use 2.12.x tag (update if you need a newer patch version)
      git checkout v2.12.1
      ./configure --prefix=/usr/local
      make -j"$(nproc)"
      make install
      # Make sure pkg-config can find rdkafka
      export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
      pkg-config --modversion rdkafka
      pkg-config --libs rdkafka
    cwd: root
    run_before_linters: true
    continue_if_failed: false

  # 3) Keep pip tooling current
  - command: python3 -m pip install --upgrade pip setuptools wheel
    cwd: root
    run_before_linters: true

  # 4) Install confluent-kafka (will compile against librdkafka 2.12.x we just built)
  - command: python3 -m pip install "confluent-kafka>=2.6.0"
    cwd: workspace
    run_before_linters: true
    continue_if_failed: false

  # 5) Install your project (do NOT silence stderr; you want to see build errors)
  - command: |
      set -eux
      if [ -f "pyproject.toml" ]; then
        python3 -m pip install -e ".[dev]" || python3 -m pip install -e .
      fi
    cwd: workspace
    run_before_linters: true

# Environment variables for linters to find installed packages
env:
  PYTHONPATH: "/usr/local/lib/python3.13/site-packages:${PYTHONPATH:-}"
  LD_LIBRARY_PATH: "/usr/local/lib:${LD_LIBRARY_PATH:-}"